### ISSUE TITLE
Including this str helpers to phel?

### ISSUE THREAD

**Issue by Chemaclass** [smeghead/phel-str#1]
What do you think about including these funcions as part of the phel-lang repo?
https://github.com/phel-lang/phel-lang/tree/main/src/phel 

It could be inside the `src/phel/str.phel` and they could be in the `(ns phel/str)` so this way they wont affect the core performance, and we can add as many str functions as we want as part of the language. 
> Similarly as we have with [json.phel](https://github.com/phel-lang/phel-lang/blob/main/src/phel/json.phel)

What do you think @smeghead, @jenshaase and @jesusvalera ?

**Comment by smeghead** [comment]
@Chemaclass 
I have no problem at all. I'm actually happy.
I think it is advantageous that many of the functions can be used in the same way even in situations where clojure experienced users use phel.

**Comment by Chemaclass** [comment]
In such a case, please, don't hesitate to create a PR to phel-lang and we can continue from there. It's your code/work, and I think it's better that it has your name in those commits. Also, if you see anything to suggest or improve, you're more than welcome! We value a lot other people ideas & contributions. That's part of the magic of OSS 😄

**Comment by smeghead** [comment]
@Chemaclass 
Thank you. I will start preparing for PR.

**Comment by smeghead** [comment]
The pull request for `phel-lang` that adds string manipulation functions has been merged and will be closed.
thank you very much.
https://github.com/phel-lang/phel-lang/pull/688
